blog/apps/post/urls.py
from django.urls import path
from apps.post import views as views

app_name = 'post'

urlpatterns = [
    path('posts/', views.PostListView.as_view(), name='post_list'),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update')
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('', include('apps.user.urls')),
    path('', include('apps.post.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/post/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
import uuid
import os




class Category(models.Model):
  title = models.CharField(max_length=50)

  def __str__(self):
   return self.title

class Post(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='post')
  title = models.CharField(max_length=200)
  slug = models.SlugField(unique=True, max_length=200, blank=True)
  content = models.TextField(max_length=10000)
  created_at = models.DateTimeField(default=timezone.now)
  updated_at = models.DateTimeField(auto_now=True)
  allow_comments = models.BooleanField(default=True)

  def __str__(self):
    return self.title
  
  @property
  def amount_comments(self):
    return self.comments.count()
  
  @property
  def amount_images(self):
    return self.images.count()
  
  def generate_unique_slug(self):
      slug = slugify(self.title)
      unique_slug = slug
      num = 1

      while Post.objects.filter(slug=unique_slug).exists():
          unique_slug = f'{slug}-{num}'
          num += 1

      return unique_slug

  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = self.generate_unique_slug()

    super().save(*args, **kwargs)  


    if not self.images.exists():
           PostImage.objects.create(post=self, image='post/default/post_default.webp')
  
class Comment(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
  content = models.TextField(max_length=50)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
   return self.content

def get_image_path(instance, filename):
  post_id = instance.post.id
  images_count = instance.post.images.count()
  # mi imagen.png
  # mi imagen    .png
  base_filename, file_extension = os.path.splitext(filename)
  # post 900945cc-248b-4781-b1e2-776fd079f641_image_1.png

  # post_89a82489-53c2-4b35-98ef-cb0b57361de0_image_1.png
  # post_89a82489-53c2-4b35-98ef-cb0b57361de0_image_2.png

  # post_c1b50579-3d7a-454d-8eca-f63c7cc0949d_image_1.png
  # post_c1b50579-3d7a-454d-8eca-f63c7cc0949d_image_2.png
  # post_c1b50579-3d7a-454d-8eca-f63c7cc0949d_image_3.png
  new_filename = f"post_{post_id}_image_{images_count + 1}{file_extension}"

  return os.path.join('post/cover/', new_filename)




class PostImage(models.Model):
  post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
  image = models.ImageField(upload_to=get_image_path)
  active = models.BooleanField(default=True)
  created_at = models.DateTimeField(default=timezone.now)
  def __str__(self):
   return f"PostImage{self.id}"

blog/apps/post/forms.py
from django import forms
from apps.post.models import Comment


class PostFilterForm(forms.Form):
    search_query = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Buscar...',
                   'class': 'w-full p-2 bg-red-200'}
        )
    )
    order_by = forms.ChoiceField(
        required=False,
        choices=(
            ('-created_at', 'Más recientes'),
            ('created_at', 'Más antiguos'),
            ('-comments_count', 'Más comentados')
        ),
        widget=forms.Select(
            attrs={'class': 'w-full p-2'}
        )
    )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment

        fields = ['content']

        labels = {
            'content':  'Comentario'
        }

        widget = {
            'content': forms.Textarea(
                attrs={
                    'rows': 3, 'placeholder': 'Escribe tu comentario...', 'class': 'p-2'
                }
            )
        }

blog/apps/post/views.py
from django.views.generic import TemplateView, ListView, DetailView
from django.db.models import Count
from apps.post.models import Post

from apps.post.forms import PostFilterForm


class PostListView(ListView):
    model = Post
    template_name = 'post/post_list.html'
    context_object_name = "posts"

    paginate_by = 1

    def get_queryset(self):
        queryset = Post.objects.all().annotate(comments_count=Count('comments'))
        search_query = self.request.GET.get('search_query', '')
        order_by = self.request.GET.get('order_by', '-created_at')

        if search_query:
            queryset = queryset.filter(title__icontains=search_query) | queryset.filter(
                author__username__icontains=search_query)

        return queryset.order_by(order_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = PostFilterForm(self.request.GET)

        if context.get('is_paginated', False):
            query_params = self.request.GET.copy()
            query_params.pop('page', None)

            pagination = {}
            page_obj = context['page_obj']
            paginator = context['paginator']

            if page_obj.number > 1:
                pagination['first_page'] = f'?{query_params.urlencode()}&page={paginator.page_range[0]}'

            if page_obj.has_previous():
                pagination['previous_page'] = f'?{query_params.urlencode()}&page={page_obj.number - 1}'

            if page_obj.has_next():
                pagination['next_page'] = f'?{query_params.urlencode()}&page={page_obj.number + 1}'

            if page_obj.number < paginator.num_pages:
                pagination['last_page'] = f'?{query_params.urlencode()}&page={paginator.num_pages}'

            context['pagination'] = pagination

        return context


class PostDetailView(TemplateView):
    template_name = 'post/post_detail.html'


class PostCreateView(TemplateView):
    template_name = 'post/post_detail.html'


class PostUpdateView(TemplateView):
    template_name = 'post/post_detail.html'


class PostDeleteView(TemplateView):
    template_name = 'post/post_detail.html'

blog/templates/post/post_detail.html
{% extends 'layouts/general_layout.html' %}

{% block title %} Post {% endblock title %}


{% block content %}
  Contenido del post
{% endblock content %}

blog/templates/post/post_list.html
{% extends 'layouts/post_layout.html' %}

{% block title %}Post | BLOG IA{% endblock title %}

{% block content %}
  <form method="get" class="flex flex-wrap sm:flex-nowrap gap-4 mb-6">
    <div class="w-full">
      {{ filter_form.search_query }}
    </div>
    <div class="w-full sm:w-[380px]">
      {{ filter_form.order_by }}
    </div>
    <button type="submit" class="w-full sm:w-[280px] bg-blue-500 text-white p-2 rounded-lg">Buscar</button>
  </form>

  <div class="grid grid-cols-1 gap-6">
    {% for post in object_list %}
      <div class="bg-gray-800 text-white rounded-2xl p-6">
        <h3 class="text-2xl uppercase font-bold">{{ post.title }}</h3>
        <p>{{ post.content }}</p>
        <p>Publicado por: <strong class="font-bold">{{ post.author.username }}</strong></p>
        <p>Fecha de publicación: {{ post.creation_date }}</p>
        <p>Comentarios permitidos: {{ post.allow_comments|yesno:"Si,No" }}</p>
        <p>Comentarios: {{ post.amount_comments }}</p>
        <div class="flex gap-2 mt-8">
          <a 
            class="bg-red-500 text-white p-2 rounded-lg" 
            href="{% url 'post:post_detail' slug=post.slug %}"
          >Ver post</a>
          <a 
            class="bg-red-500 text-white p-2 rounded-lg" 
            href="{% url 'post:post_delete' slug=post.slug %}"
          >Eliminar post</a>
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="mt-4">
    {% if is_paginated %}
      <div class="flex justify-center items-center gap-2">
        {% if pagination.previous_page %}
          <a href="{{ pagination.previous_page }}" class="w-16 text-xs text-center bg-blue-500 text-white p-1 rounded-md">Anterior</a>
        {% else %}
          <span class="w-16 text-xs text-center bg-gray-500 text-white p-1 rounded-md">Anterior</span>
        {% endif %}

        <span class="w-10 text-center text-lg font-semibold">{{ page_obj.number }}</span>

        {% if pagination.next_page %}
          <a href="{{ pagination.next_page }}" class="w-16 text-xs text-center bg-blue-500 text-white p-1 rounded-md">Siguiente</a>
        {% else %}
          <span class="w-16 text-xs text-center bg-gray-500 text-white p-1 rounded-md">Siguiente</span>
        {% endif %}
      </div>
    {% endif %}
  </div>
{% endblock content %}
  